<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>nlex</string>
   </array>
  <key>name</key>
  <string>NLex</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.NLex</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(#.*$)</string>
          <key>name</key>
          <string>comment.NLex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(option)(\s+)(\w+)(\s+)(on|off)$</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.class.NLex</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword.other.special-method.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(tag)(\s*)(pos)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\w+)(\s*)(::)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.class.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\w+)(\s*)(:-)(\s*)(&quot;[^\x{0022}]*&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.class.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>entity.name.type.class.NLex</string>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\w+)(\s*)(:-)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.class.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\w+)(\s*)(--)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.class.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(normalise)(\s+)(\{)((?:[^\x{007d}]|\\})*)(\})(\s+)(to)(.)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>constant.character.NLex</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>keyword.NLex</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>constant.character.NLex</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>constant.character.NLex</string>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(stopword)(\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#stopwords</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(ignore)(\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#ignores</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>ignores</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\w+)(\s*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.class.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>kaleid</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\d+|\d*\.\d+)</string>
          <key>name</key>
          <string>constant.numeric.comment.block.preprocessor.NLex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&quot;)((?:[^\x{0022}]|\\&quot;)*)(&quot;)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.comment.block.preprocessor.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.comment.block.preprocessor.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.comment.block.preprocessor.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b(?:if|then|else|def|extern|for|in|var|global|while)\b)</string>
          <key>name</key>
          <string>keyword.comment.block.preprocessor.NLex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)(\s*\(\s*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.comment.block.preprocessor.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.operator.comment.block.preprocessor.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\)|,)</string>
          <key>name</key>
          <string>keyword.operator.comment.block.preprocessor.NLex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\w+)</string>
          <key>name</key>
          <string>entity.name.function.comment.block.preprocessor.NLex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0022}\w]+)</string>
          <key>name</key>
          <string>keyword.operator.comment.block.preprocessor.NLex</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#tag_pos</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regularExpression</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^|\)|\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\s*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regularExpression</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^|\)|\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(-?)(&quot;)(?:(\\uc\{[^\x{007d}]*\})|((?:[^\x{0022}]|\\&quot;)*))(&quot;)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.class.NLex</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>string.NLex</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__6</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>regularExpression</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\(\?\#)([^\x{0029}]*)(\))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>comment.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\(\?.)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regularExpression</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^|\)|\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regularExpression</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^|\)|\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\{)(\d+)(,?)(\d+)?(\})</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.other.link.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>string.other.link.NLex</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\||\\[^pgE])</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.other.link.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regularExpression</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^|\)|\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\\E\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.comment.block.preprocessor.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#kaleid</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.comment.block.preprocessor.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\\g)(\d+)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.other.link.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regularExpression</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^|\)|\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\\p)(\{)(\w+)(\})</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.other.link.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regularExpression</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^|\)|\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\{\{)(\w+)(\}\})</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.class.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regularExpression__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.regexp.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\+|\*|\?)</string>
          <key>name</key>
          <string>string.regexp.NLex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.)</string>
          <key>name</key>
          <string>constant.character.NLex</string>
        </dict>
       </array>
    </dict>
    <key>regularExpression__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([^\x{005c}\]])</string>
          <key>name</key>
          <string>string.regexp.NLex</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\\)(.)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.other.link.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>string.other.link.NLex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>stopwords</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(-?)(&quot;)([^\x{0022}]*)(&quot;)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.NLex</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>tag_pos</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(every)(\s*)(\d+)(\s*)(tokens?)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword.NLex</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(from)(\s*)(&quot;(?:[^\x{0022}]|\\&quot;)*&quot;)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>string.NLex</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(with)?(\s*)(delimiter)(\s*)(\w+)(\{)([^\x{007b}]+)(\})</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>3</key>
            <dict>
              <key>name</key>
              <string>keyword punctuation.NLex</string>
            </dict>
            <key>4</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>5</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.class.NLex</string>
            </dict>
            <key>6</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
            <key>7</key>
            <dict>
              <key>name</key>
              <string>constant.character.NLex</string>
            </dict>
            <key>8</key>
            <dict>
              <key>name</key>
              <string>punctuation.NLex</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
